---
- hosts: all

  become: true
  
  tasks:
    - name: Check /tmp freespace
      shell: df /tmp --output\=pcent | tail -1
      register: tmp_usedpercent
    
    - fail:
        msg: /tmp does not have the minimum space required to continue (3Gb requested). 
      when: tmp_usedpercent.stdout|float > 80

    - debug:
        msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
        msg: "System Disk Usage {{ tmp_usedpercent.stdout }}"
        

